# Generated by Django 5.2.1 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionNeWaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inmovilizacion', 'Control por inmovilización'), ('luxacion', 'Control por luxación'), ('estrangulacion', 'Control por estrangulación')], max_length=20, verbose_name='Tipo')),
                ('es_combinacion', models.BooleanField(default=False, verbose_name='Es combinación')),
                ('descripcion_combinacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de combinación')),
                ('tiempo', models.DurationField(verbose_name='Tiempo de la acción')),
            ],
            options={
                'verbose_name': 'Acción Ne Waza',
                'verbose_name_plural': 'Acciones Ne Waza',
            },
        ),
        migrations.CreateModel(
            name='AccionTashiWaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ashi_waza', 'Ashi Waza'), ('koshi_waza', 'Koshi Waza'), ('kata_te_waza', 'Kata Te Waza'), ('sutemi_waza', 'Sutemi Waza')], max_length=20, verbose_name='Tipo')),
                ('resultado', models.CharField(choices=[('wazari', 'Wazari (Wz)'), ('yuko', 'Yuko (Y)'), ('ippon', 'Ippon (Ip)'), ('negativo', 'Negativo')], max_length=10, verbose_name='Resultado')),
                ('es_combinacion', models.BooleanField(default=False, verbose_name='Es combinación')),
                ('descripcion_combinacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de combinación')),
                ('tiempo', models.DurationField(verbose_name='Tiempo de la acción')),
            ],
            options={
                'verbose_name': 'Acción Tashi Waza',
                'verbose_name_plural': 'Acciones Tashi Waza',
            },
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('shido', 'Shido'), ('hansokumake', 'Hansokumake')], max_length=20, verbose_name='Tipo')),
                ('tiempo', models.DurationField(verbose_name='Tiempo de la amonestación')),
            ],
            options={
                'verbose_name': 'Amonestación',
                'verbose_name_plural': 'Amonestaciones',
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField(blank=True, null=True, verbose_name='Duración del combate')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
            ],
            options={
                'verbose_name': 'Combate',
                'verbose_name_plural': 'Combates',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
