# Generated by Django 5.2.1 on 2025-05-31 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combates', '0001_initial'),
        ('competiciones', '0001_initial'),
        ('competidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionnewaza',
            name='competidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ne_waza', to='competidores.competidor'),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='competidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_tashi_waza', to='competidores.competidor'),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='competidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones', to='competidores.competidor'),
        ),
        migrations.AddField(
            model_name='combate',
            name='competicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='competiciones.competicion'),
        ),
        migrations.AddField(
            model_name='combate',
            name='competidor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_como_competidor1', to='competidores.competidor'),
        ),
        migrations.AddField(
            model_name='combate',
            name='competidor2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_como_competidor2', to='competidores.competidor'),
        ),
        migrations.AddField(
            model_name='combate',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combates_ganados', to='competidores.competidor'),
        ),
    ]
