# Generated by Django 5.2.1 on 2025-05-31 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='combate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones', to='combates.combate'),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='combate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_tashi_waza', to='combates.combate'),
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='combate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ne_waza', to='combates.combate'),
        ),
    ]
