# Generated by Django 5.2.1 on 2025-06-05 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0003_initial'),
        ('competidores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionnewaza',
            name='descripcion_combinacion',
        ),
        migrations.RemoveField(
            model_name='accionnewaza',
            name='es_combinacion',
        ),
        migrations.RemoveField(
            model_name='acciontashiwaza',
            name='descripcion_combinacion',
        ),
        migrations.RemoveField(
            model_name='acciontashiwaza',
            name='es_combinacion',
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='efectiva',
            field=models.BooleanField(default=True, verbose_name='Efectiva'),
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ne_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='efectiva',
            field=models.BooleanField(default=True, verbose_name='Efectiva'),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_tashi_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combate',
            name='iniciado',
            field=models.BooleanField(default=False, verbose_name='Iniciado'),
        ),
        migrations.AlterField(
            model_name='acciontashiwaza',
            name='tipo',
            field=models.CharField(choices=[('ashi_waza', 'Ashi Waza'), ('koshi_waza', 'Koshi Waza'), ('te_waza', 'Te Waza'), ('sutemi_waza', 'Sutemi Waza')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='AccionCombinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción de la combinación')),
                ('tiempo', models.DurationField(verbose_name='Tiempo de la acción')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_combinadas', to='combates.combate')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_combinadas', to='competidores.competidor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_combinadas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción Combinada',
                'verbose_name_plural': 'Acciones Combinadas',
            },
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='accion_combinada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ne', to='combates.accioncombinada'),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='accion_combinada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_tashi', to='combates.accioncombinada'),
        ),
    ]
