# Generated by Django 4.2.11 on 2025-06-06 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('combates', '0004_remove_accionnewaza_descripcion_combinacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciontashiwaza',
            name='resultado',
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='duracion_control',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración del control'),
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='puntuacion',
            field=models.CharField(choices=[('ippon', 'Ippon'), ('waza_ari', 'Waza-ari'), ('sin_puntuacion', 'Sin puntuación')], default='sin_puntuacion', max_length=15, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='accionnewaza',
            name='tecnica',
            field=models.CharField(choices=[('kesa_gatame', 'Kesa-gatame'), ('kata_gatame', 'Kata-gatame'), ('kami_shiho_gatame', 'Kami-shiho-gatame'), ('kuzure_kami_shiho_gatame', 'Kuzure-kami-shiho-gatame'), ('yoko_shiho_gatame', 'Yoko-shiho-gatame'), ('tate_shiho_gatame', 'Tate-shiho-gatame'), ('kuzure_kesa_gatame', 'Kuzure-kesa-gatame'), ('uki_gatame', 'Uki-gatame'), ('ura_gatame', 'Ura-gatame'), ('ushiro_kesa_gatame', 'Ushiro-kesa-gatame'), ('nami_juji_jime', 'Nami-juji-jime'), ('gyaku_juji_jime', 'Gyaku-juji-jime'), ('kata_juji_jime', 'Kata-juji-jime'), ('hadaka_jime', 'Hadaka-jime'), ('okuri_eri_jime', 'Okuri-eri-jime'), ('kataha_jime', 'Kataha-jime'), ('do_jime', 'Do-jime'), ('sode_guruma_jime', 'Sode-guruma-jime'), ('kata_te_jime', 'Kata-te-jime'), ('ryo_te_jime', 'Ryo-te-jime'), ('tsukkomi_jime', 'Tsukkomi-jime'), ('sankaku_jime', 'Sankaku-jime'), ('ude_garami', 'Ude-garami'), ('ude_hishigi_juji_gatame', 'Ude-hishigi-juji-gatame'), ('ude_hishigi_ude_gatame', 'Ude-hishigi-ude-gatame'), ('ude_hishigi_hiza_gatame', 'Ude-hishigi-hiza-gatame'), ('ude_hishigi_waki_gatame', 'Ude-hishigi-waki-gatame'), ('ude_hishigi_hara_gatame', 'Ude-hishigi-hara-gatame'), ('ude_hishigi_ashi_gatame', 'Ude-hishigi-ashi-gatame'), ('ude_hishigi_te_gatame', 'Ude-hishigi-te-gatame'), ('ude_hishigi_sankaku_gatame', 'Ude-hishigi-sankaku-gatame'), ('ashi_garami', 'Ashi-garami')], default='seoi_nage', max_length=30, verbose_name='Técnica específica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='puntuacion',
            field=models.CharField(choices=[('ippon', 'Ippon'), ('waza_ari', 'Waza-ari'), ('sin_puntuacion', 'Sin puntuación')], default='sin_puntuacion', max_length=15, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='acciontashiwaza',
            name='tecnica',
            field=models.CharField(choices=[('seoi_nage', 'Seoi-nage'), ('ippon_seoi_nage', 'Ippon-seoi-nage'), ('seoi_otoshi', 'Seoi-otoshi'), ('tai_otoshi', 'Tai-otoshi'), ('kata_guruma', 'Kata-guruma'), ('sukui_nage', 'Sukui-nage'), ('obi_otoshi', 'Obi-otoshi'), ('uki_otoshi', 'Uki-otoshi'), ('sumi_otoshi', 'Sumi-otoshi'), ('yama_arashi', 'Yama-arashi'), ('obi_tori_gaeshi', 'Obi-tori-gaeshi'), ('morote_gari', 'Morote-gari'), ('kuchiki_taoshi', 'Kuchiki-taoshi'), ('kibisu_gaeshi', 'Kibisu-gaeshi'), ('uchi_mata_sukashi', 'Uchi-mata-sukashi'), ('ko_uchi_gaeshi', 'Ko-uchi-gaeshi'), ('uki_goshi', 'Uki-goshi'), ('o_goshi', 'O-goshi'), ('koshi_guruma', 'Koshi-guruma'), ('tsurikomi_goshi', 'Tsurikomi-goshi'), ('sode_tsurikomi_goshi', 'Sode-tsurikomi-goshi'), ('harai_goshi', 'Harai-goshi'), ('tsuri_goshi', 'Tsuri-goshi'), ('hane_goshi', 'Hane-goshi'), ('utsuri_goshi', 'Utsuri-goshi'), ('ushiro_goshi', 'Ushiro-goshi'), ('ashi_guruma', 'Ashi-guruma'), ('de_ashi_harai', 'De-ashi-harai'), ('harai_tsurikomi_ashi', 'Harai-tsurikomi-ashi'), ('hiza_guruma', 'Hiza-guruma'), ('kosoto_gake', 'Kosoto-gake'), ('kosoto_gari', 'Kosoto-gari'), ('kouchi_gari', 'Kouchi-gari'), ('o_guruma', 'O-guruma'), ('okuri_ashi_harai', 'Okuri-ashi-harai'), ('osoto_gari', 'Osoto-gari'), ('osoto_guruma', 'Osoto-guruma'), ('osoto_otoshi', 'Osoto-otoshi'), ('ouchi_gari', 'Ouchi-gari'), ('sasae_tsurikomi_ashi', 'Sasae-tsurikomi-ashi'), ('uchi_mata', 'Uchi-mata'), ('osoto_gaeshi', 'Osoto-gaeshi'), ('ouchi_gaeshi', 'Ouchi-gaeshi'), ('hane_goshi_gaeshi', 'Hane-goshi-gaeshi'), ('harai_goshi_gaeshi', 'Harai-goshi-gaeshi'), ('uchi_mata_gaeshi', 'Uchi-mata-gaeshi'), ('tsubame_gaeshi', 'Tsubame-gaeshi'), ('hikikomi_gaeshi', 'Hikikomi-gaeshi'), ('sumi_gaeshi', 'Sumi-gaeshi'), ('tawara_gaeshi', 'Tawara-gaeshi'), ('tomoe_nage', 'Tomoe-nage'), ('ura_nage', 'Ura-nage'), ('daki_wakare', 'Daki-wakare'), ('hane_makikomi', 'Hane-makikomi'), ('harai_makikomi', 'Harai-makikomi'), ('osoto_makikomi', 'Osoto-makikomi'), ('soto_makikomi', 'Soto-makikomi'), ('tani_otoshi', 'Tani-otoshi'), ('uchi_makikomi', 'Uchi-makikomi'), ('uchi_mata_makikomi', 'Uchi-mata-makikomi'), ('uki_waza', 'Uki-waza'), ('yoko_gake', 'Yoko-gake'), ('yoko_guruma', 'Yoko-guruma'), ('yoko_otoshi', 'Yoko-otoshi'), ('yoko_wakare', 'Yoko-wakare'), ('ko_uchi_makikomi', 'Ko-uchi-makikomi'), ('kani_basami', 'Kani-basami (Prohibida)'), ('kawazu_gake', 'Kawazu-gake (Prohibida)')], default='seoi_nage', max_length=30, verbose_name='Técnica específica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accionnewaza',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ne_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accionnewaza',
            name='tipo',
            field=models.CharField(choices=[('osaekomi_waza', 'Osaekomi-waza (Inmovilización)'), ('shime_waza', 'Shime-waza (Estrangulación)'), ('kansetsu_waza', 'Kansetsu-waza (Luxación)')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='acciontashiwaza',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_tashi_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acciontashiwaza',
            name='tipo',
            field=models.CharField(choices=[('te_waza', 'Te-waza (Técnicas de mano)'), ('koshi_waza', 'Koshi-waza (Técnicas de cadera)'), ('ashi_waza', 'Ashi-waza (Técnicas de pie)'), ('ma_sutemi_waza', 'Ma-sutemi-waza (Sacrificio frontal)'), ('yoko_sutemi_waza', 'Yoko-sutemi-waza (Sacrificio lateral)')], max_length=20, verbose_name='Tipo'),
        ),
    ]
