# Generated by Django 4.2.11 on 2025-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0005_remove_acciontashiwaza_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciontashiwaza',
            name='puntuacion',
            field=models.CharField(choices=[('ippon', 'Ippon'), ('waza_ari', 'Waza-ari'), ('yuko', 'Yuko'), ('sin_puntuacion', 'Sin puntuación')], default='sin_puntuacion', max_length=15, verbose_name='Puntuación'),
        ),
    ]
