# Generated by Django 4.2.11 on 2025-06-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0006_alter_acciontashiwaza_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciontashiwaza',
            name='tipo',
            field=models.CharField(choices=[('kata_te_waza', 'Kata-te-waza (Técnicas de mano)'), ('koshi_waza', 'Koshi-waza (Técnicas de cadera)'), ('ashi_waza', 'Ashi-waza (Técnicas de pie)'), ('ma_sutemi_waza', 'Ma-sutemi-waza (Sacrificio frontal)'), ('yoko_sutemi_waza', 'Yoko-sutemi-waza (Sacrificio lateral)')], max_length=20, verbose_name='Tipo'),
        ),
    ]
