# Generated by Django 4.2.11 on 2025-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0007_alter_acciontashiwaza_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncombinada',
            name='descripcion_detallada',
            field=models.TextField(blank=True, verbose_name='Descripción detallada con técnicas'),
        ),
        migrations.AddField(
            model_name='accioncombinada',
            name='efectiva',
            field=models.BooleanField(default=False, verbose_name='Efectiva'),
        ),
        migrations.AddField(
            model_name='accioncombinada',
            name='puntuacion',
            field=models.CharField(choices=[('sin_puntuacion', 'Sin puntuación'), ('yuko', 'Yuko'), ('waza_ari', 'Waza-ari'), ('ippon', 'Ippon')], default='sin_puntuacion', max_length=20, verbose_name='Puntuación'),
        ),
    ]
