# Generated by Django 4.2.11 on 2025-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0009_alter_amonestacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas del combate', null=True, verbose_name='Observaciones del combate'),
        ),
    ]
