# Generated by Django 5.2.1 on 2025-05-31 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competiciones', '0001_initial'),
        ('competidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('individual', 'Reporte Individual'), ('comparativo', 'Reporte Comparativo')], max_length=20, verbose_name='Tipo de reporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin del período')),
                ('competiciones', models.ManyToManyField(blank=True, related_name='reportes', to='competiciones.competicion')),
                ('competidores', models.ManyToManyField(related_name='reportes', to='competidores.competidor')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_combates', models.PositiveIntegerField(default=0, verbose_name='Total de combates')),
                ('combates_ganados', models.PositiveIntegerField(default=0, verbose_name='Combates ganados')),
                ('combates_perdidos', models.PositiveIntegerField(default=0, verbose_name='Combates perdidos')),
                ('total_ataques_tashi_waza', models.PositiveIntegerField(default=0, verbose_name='Total de ataques Tashi Waza')),
                ('ataques_positivos', models.PositiveIntegerField(default=0, verbose_name='Ataques positivos')),
                ('ataques_negativos', models.PositiveIntegerField(default=0, verbose_name='Ataques negativos')),
                ('wazari', models.PositiveIntegerField(default=0, verbose_name='Wazari')),
                ('yuko', models.PositiveIntegerField(default=0, verbose_name='Yuko')),
                ('ippon', models.PositiveIntegerField(default=0, verbose_name='Ippon')),
                ('ashi_waza', models.PositiveIntegerField(default=0, verbose_name='Ashi Waza')),
                ('koshi_waza', models.PositiveIntegerField(default=0, verbose_name='Koshi Waza')),
                ('kata_te_waza', models.PositiveIntegerField(default=0, verbose_name='Kata Te Waza')),
                ('sutemi_waza', models.PositiveIntegerField(default=0, verbose_name='Sutemi Waza')),
                ('combinaciones', models.PositiveIntegerField(default=0, verbose_name='Combinaciones')),
                ('total_acciones_ne_waza', models.PositiveIntegerField(default=0, verbose_name='Total de acciones Ne Waza')),
                ('inmovilizaciones', models.PositiveIntegerField(default=0, verbose_name='Inmovilizaciones')),
                ('luxaciones', models.PositiveIntegerField(default=0, verbose_name='Luxaciones')),
                ('estrangulaciones', models.PositiveIntegerField(default=0, verbose_name='Estrangulaciones')),
                ('shido', models.PositiveIntegerField(default=0, verbose_name='Shido')),
                ('hansokumake', models.PositiveIntegerField(default=0, verbose_name='Hansokumake')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='competidores.competidor')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='estadisticas.reporte')),
            ],
            options={
                'verbose_name': 'Estadística de Competidor',
                'verbose_name_plural': 'Estadísticas de Competidores',
            },
        ),
    ]
