# Generated by Django 4.2.11 on 2025-06-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticacompetidor',
            options={'ordering': ['-id'], 'verbose_name': 'Estadística de Competidor', 'verbose_name_plural': 'Estadísticas de Competidores'},
        ),
    ]
