# Generated by Django 4.2.11 on 2025-06-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_alter_reporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticacompetidor',
            name='ataques_combinados',
            field=models.PositiveIntegerField(default=0, verbose_name='Ataques Combinados'),
        ),
        migrations.AddField(
            model_name='estadisticacompetidor',
            name='tecnicas_negativas_combinadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Técnicas Negativas en Combinaciones'),
        ),
        migrations.AddField(
            model_name='estadisticacompetidor',
            name='tecnicas_positivas_combinadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Técnicas Positivas en Combinaciones'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Reporte Individual'), ('comparativo', 'Reporte Comparativo')], max_length=20, verbose_name='Tipo de reporte'),
        ),
    ]
