# Generated by Django 4.2.11 on 2025-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0004_estadisticacompetidor_ataques_combinados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticacompetidor',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas del competidor', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='estadisticacompetidor',
            name='recomendaciones',
            field=models.TextField(blank=True, help_text='Recomendaciones de entrenamiento', null=True, verbose_name='Recomendaciones'),
        ),
    ]
