# Generated by Django 5.2.1 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('evento', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('combate_oficial', 'Combate oficial')], max_length=20, verbose_name='Evento')),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20, verbose_name='Tipo de competencia')),
                ('cantidad_atletas', models.PositiveIntegerField(verbose_name='Cantidad de atletas')),
                ('cantidad_combates_planificados', models.PositiveIntegerField(verbose_name='Cantidad de combates a realizar')),
                ('cantidad_combates_realizados', models.PositiveIntegerField(default=0, verbose_name='Número de combates realizados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Competición',
                'verbose_name_plural': 'Competiciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
