# Generated by Django 5.2.1 on 2025-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0003_competicion_competidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='cantidad_combates_planificados',
            field=models.IntegerField(default=0),
        ),
    ]
