# Generated by Django 4.2.11 on 2025-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0005_competicion_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='competicion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
