# Generated by Django 5.2.1 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('division_peso', models.CharField(max_length=10, verbose_name='División de peso')),
                ('categoria', models.CharField(choices=[('sub21_juvenil', 'Sub 21 - Juvenil'), ('sub21_primera', 'Sub 21 - 1ra categoría')], max_length=20, verbose_name='Categoría')),
                ('anos_experiencia', models.PositiveIntegerField(verbose_name='Años de experiencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Competidor',
                'verbose_name_plural': 'Competidores',
                'ordering': ['nombre'],
            },
        ),
    ]
