# Generated by Django 4.2.11 on 2025-06-16 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competidores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='anos_experiencia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Años de experiencia'),
        ),
    ]
