# Generated by Django 4.2.11 on 2025-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competidores', '0003_alter_competidor_anos_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='competidor',
            name='identificacion_personal',
            field=models.CharField(blank=True, help_text='Carnet de identidad del competidor', max_length=11, null=True, verbose_name='Identificación Personal (CI)'),
        ),
    ]
