# Generated by Django 4.2.11 on 2025-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competidores', '0004_competidor_identificacion_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='identificacion_personal',
            field=models.CharField(help_text='Carnet de identidad del competidor', max_length=11, unique=True, verbose_name='Identificación Personal (CI)'),
        ),
    ]
