# Generated by Django 4.2.11 on 2025-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competidores', '0005_alter_competidor_identificacion_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='competidor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el competidor está activo en el sistema', verbose_name='Activo'),
        ),
    ]
